<?= $this->doctype() ?>
<html lang="en">

<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8" />
    <?= $this->headTitle('Laminas Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendName('description', 'getlaminas.in')
        ->appendName('author', 'getlaminas.in')
    ?>
    <!-- FONT
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href="//fonts.googleapis.com/css?family=Fira+Code:400,300,600" rel="stylesheet" type="text/css" />

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="" />
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . 'assets/images/favicon.png'])
        ->prependStylesheet($this->basePath('assets/dist/app.min.css'))

    ?>

    <!-- <script type="text/javascript" src="" defer></script> -->
    <!-- Scripts -->
    <?= $this->headScript()
        ->setAllowArbitraryAttributes(true)
        ->prependFile($this->basePath('assets/dist/app.min.js'), null, ["defer" => "true"])
    ?>
    <!--    github-fork-ribbon-css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css" />
</head>

<body>
    <a class="fork-me" href="https://github.com/vrkansagara/laminas-adminpanel" target="_blank">Fork me on GitHub</a>

    <div class="container">
        <?= $this->navigation('navigation')
            ->menu()
            ->setMinDepth(0)
            ->setMaxDepth(0)
            ->setUlClass('nav navbar-nav') ?>
    </div>

    <div class="container">
        <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
        <!-- Navigation bar -->
        <?= $this->content ?>
    </div>

    <footer class="footer">
        <div class="container">
            <span class="sticky-footer  text-muted">
                <p>&copy; 2005 - <?= date('Y') ?> by <a href="https://github.com/vrkansagara/laminas-adminpanel">Laminas Admin Panel</a>. All rights reserved.</p>
            </span>
        </div>
    </footer>
    <?= $this->inlineScript() ?>
</body>

</html>