<?php
namespace JsValidation\Controller;

use JsValidation\Form\PostForm;
use Laminas\Mvc\Controller\AbstractActionController;

class IndexController extends AbstractActionController
{

    /**
     * @var PostForm
     */
    private $form;

    /**
     * IndexController constructor.
     * @param PostForm $form
     */
    public function __construct(
        PostForm $form
    )
    {
        $this->form = $form;
    }

    public function indexAction()
    {
        echo '<pre>'; print_r('here'); echo __FILE__; echo __LINE__; exit;
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

}