<div class="container">
    <h2>About this project</h2>
    <p>This project based on three core pillars.</p>
    <ul>
        <li>Speed</li>
        <li>Performace</li>
        <li>Accuracy</li>
    </ul>


    <h3>Techonology used in this project</h3>
    <ul>
        <li>Bootstrap4</li>
        <li>Material design</li>
        <li>Webpack</li>
        <li>PHP</li>
        <li>MySql</li>
        <li>Sqlite</li>
        <li>Nginx</li>
    </ul>
</div>
