<div class="container">
    <section class="header">
        <h2 class="title">Get Laminas</h2>
        <h3>Something is coming up for enterprise.</h3>
        <a class="button button-primary" href="https://github.com/vrkansagara/laminas-adminpanel">Download</a>
        <div class="value-props row">
            <div class="four columns value-prop">
                Design
            </div>
            <div class="four columns value-prop">
                Develop
            </div>
            <div class="four columns value-prop">
                Deploy
            </div>
        </div>
    </section>
</div>
