<div class="container">
    <main role="main" class="flex-shrink-0">
        <div class="container mt-5 text-center">
            <h1 class="mt-0">Admin Panel for Laminas</h1>
            <h2 class="lead">Something is coming up for enterprise.</h2>
            <a class="btn btn-lg btn-primary" href=https://github.com/vrkansagara/laminas-adminpanel
               role="button">Download</a>
        </div>
    </main>
</div>