<div class="container">
    <div class="jumbotron mt-3">
        <h1 class="mt-5 text-left">Admin Panel for Laminas</h1>
        <h2 class="mt-2 lead text-uppercase text-left bg-info">This project is under development mode</h2>
        <p><a class="btn btn-primary btn-lg" href="https://github.com/vrkansagara/laminas-adminpanel" role="button">Learn more »</a></p>
    </div>
</div>

<div class="container">
    <div class="row mt-5">
        <div class="col-lg-4">
            <h2>Speed</h2>
            <p>When it comes to web application, speed is matter and why it matter. When you speed up service, people become more engaged - and when people become more engaged, they approach more services and product.</p>
            <p><a class="btn btn-secondary" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <h2>Performace</h2>
            <p>Performance is about retaining users.We want users to interact meaningfully with what we build. If it's a blog, we want people to read posts. If it's an online store, we want them to buy stuff. If it's a social network, we want them to interact with each other.</p>
            <p><a class="btn btn-secondary" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <h2>Accuracy</h2>
            <p>While delivering content to visitors it's need more accurate speed and performance at a same time so we need to mainly focus on accuracy</p>
            <p><a class="btn btn-secondary" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
    </div>
</div>
