<div class="container">
    <main role="main">
        <div class="row">
            <div class="col-md-8 blog-main">
                <h3 class="pb-3 mb-4 font-italic border-bottom">
                    From the Firehose
                    <a class="btn btn-sm btn-primary" href="<?= $this->url('blog/add') ?>">+</a>
                </h3>
                <?php foreach ($this->paginator as $post) : ?>
                    <div class="blog-post">
                        <h2 class="blog-post-title">
                            <a href="<?= $this->url('blog/detail', ['id' => $post->getId()]) ?>">
                                <?= $post->getTitle() ?>
                            </a>
                        </h2>
                        <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>
                        <a class="btn btn-sm btn-default"
                           href="<?= $this->url('blog/edit', ['id' => $post->getId()]) ?>">Edit</a>
                        <a class="btn btn-sm btn-danger"
                           href="<?= $this->url('blog/delete', ['id' => $post->getId()]) ?>">Delete</a>
                    </div>
                    <!-- /.blog-post -->
                <?php endforeach ?>
            </div><!-- /.blog-main -->

            <aside class="col-md-4 blog-sidebar">
                <div class="p-3 mb-3 bg-light rounded">
                    <h4 class="font-italic">About</h4>
                    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur
                        purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                </div>

                <div class="p-3">
                    <h4 class="font-italic">Archives</h4>
                    <ol class="list-unstyled mb-0">
                        <li><a href="#">March 2014</a></li>
                    </ol>
                </div>

                <div class="p-3">
                    <h4 class="font-italic">Elsewhere</h4>
                    <ol class="list-unstyled">
                        <li><a href="#">GitHub</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ol>
                </div>
            </aside><!-- /.blog-sidebar -->

        </div><!-- /.row -->
    </main>
    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/paginator', ['route' => $this->url]) ?>
</div>

