<!--<div class="d-flex justify-content-center" >-->
<!--    <a style="transform: rotate(0deg);font-family: Quicksand, sans-serif;z-index: 1100;color: #fff;background-color: #68b60f;border: 1px solid #888;" href="https://github.com/vrkansagara/laminas-adminpanel" target="_blank">Fork me on GitHub</a>-->
<!--</div>-->

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Get Laminas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <?= $this->navigation('navigation')->menu()
                    ->setOnlyActiveBranch(true)
                    ->setRenderParents(true)
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setUlClass('navbar-nav mr-auto')
//        ->setPartial('partial/nav')
//        ->renderSubMenu(null, 'sidebar', 4)
                    ->render();
                ?>
            </ul>
            <!--            <form class="form-inline mt-2 mt-md-0">-->
            <!--                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
            <!--            </form>-->
        </div>
    </nav>

</header>