<?php
$this->headTitle('Posts');
?>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Posts
            </h3>
            <p>
                <a href="<?= $this->url('blog/posts', ['action' => 'add']); ?>">
                    Add post
                </a>
            </p>
            <?php foreach ($posts as $post) : ?>
            <div class="blog-post">
                <h2 class="blog-post-title">
                    <a href="<?= $this->url('blog/posts', ['action' => 'view', 'id' => $post->getId()]); ?>">
                        <?= $this->escapeHtml($post->getTitle()); ?>
                    </a>
                </h2>
                <p class="blog-post-meta">Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?>
                    | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?></p>

                <?= $converter->convertToHtml($this->escapeHtml($post->getContent())); ?>
                <p class="comments-header">
                    <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?> |
                    <a href="<?= $this->url(
                        'blog/posts',
                        ['action' => 'view', 'id' => $post->getId()],
                        ['fragment' => 'comment']
                    ); ?>">
                        Add new comment
                    </a>
                </p>
            </div>
            <!-- /.blog-post -->
            <?php endforeach; ?>
        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">New updates.</p>
            </div>
            <div class="p-3">
                <h4 class="font-italic">Popular Tags</h4>
                <?php foreach ($this->tagCloud as $tagName => $frequency) : ?>

                    <a href="<?= $this->url(
                        'blog',
                        ['action' => 'index'],
                        ['query' => ['tag' => $tagName]]
                    ); ?>">

                            <span style="font-size:<?= $this->escapeHtml(0.9 + $frequency * 3) ?>em">
                                <?= $this->escapeHtml($tagName); ?>
                            </span>

                    </a>

                <?php endforeach; ?>
            </div>
        </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->
    <?= $this->paginationControl($posts, 'sliding', 'partial/paginator', ['route' => $this->url]) ?>
</main>


