<?= $this->doctype() ?>
<html lang="en" class="h-100">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8"/>
    <?= $this->headTitle('Laminas Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendName('description', 'getlaminas.in')
        ->appendName('author', 'getlaminas.in')
    ?>
    <!-- FONT
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href="//fonts.googleapis.com/css?family=Fira+Code:400,300,600" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:600&display=swap" rel="stylesheet">
    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href=""/>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath('/') . 'assets/images/favicon.png'])
        ->prependStylesheet($this->basePath('assets/dist/app.min.css'))

    ?>
    <!--    github-fork-ribbon-css-->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css"/>
</head>

<body class="d-flex flex-column h-100">
<div class="container">
    <?= $this->navigation('navigation')->menu()
        ->setOnlyActiveBranch(true)
        ->setRenderParents(true)
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setUlClass('d-inline-flex')
//        ->setPartial('partial/nav')
//        ->renderSubMenu(null, 'sidebar', 4)
        ->render();
    ?>
</div>
<div class="container">
    <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
    <!-- Navigation bar -->
    <?= $this->content ?>
</div>


<footer class="footer mt-auto py-3">
    <div class="container">
               <span class="sticky-footer  text-muted">
               &copy; 2005 - <?= date('Y') ?> by <a href="https://github.com/vrkansagara/laminas-adminpanel">Laminas Admin Panel</a>. <?= $this->translate('All rights reserved.') ?>.
            </span>
    </div>
</footer>
<!-- Scripts -->
<?= $this->headScript()
    ->setAllowArbitraryAttributes(true)
    ->prependFile($this->basePath('assets/dist/app.min.js'), null, ['defer' => true])
?>
<?= $this->inlineScript() ?>
</body>

</html>