<?= $this->doctype() ?>
<html lang="en" class="h-100">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8"/>
    <?= $this->headTitle('Laminas Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendName('description', 'getlaminas.in')
        ->appendName('author', 'getlaminas.in')
    ?>
    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href=""/>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath('/') . 'dist/images/favicon.png'])
//        ->prependStylesheet($this->basePath('assets/dist/app.min.css'))
        ->prependStylesheet($this->basePath('dist/css/app.css'))

    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->setAllowArbitraryAttributes(true)
//        ->prependFile($this->basePath('dist/app.min.js'), null, ['defer' => true])
        ->prependFile($this->basePath('dist/js/app.js'), null, ['defer' => true])
        ->prependFile($this->basePath('dist/js/manifest.js'), null, ['defer' => true])
        ->prependFile($this->basePath('dist/js/vendor.js'), null, ['defer' => true])
    ?>
</head>

<body class="d-flex flex-column h-100">
<div id="page-loader" class="page-loader-wrapper">
    <div class="loader">
        <div>
            <div class="lds-ripple">
                <div></div>
                <div></div>
            </div>
            <p>Please wait...</p></div>
    </div>
</div>
<div id="app"></div>

<div class="container">
    <?= $this->navigation('navigation')->menu()
        ->setRenderParents(true)
        ->setMinDepth(0)
        ->setMaxDepth(0)
        ->setUlClass('d-inline-flex')
//        ->setPartial('partial/nav')
//        ->renderSubMenu(null, 'sidebar', 4)
        ->render();
    ?>
</div>
<?php

// $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>

<?= $this->content ?>

<footer class="footer mt-auto py-3">
    <div class="container">
               <span class="sticky-footer  text-muted">
               &copy; 2019 - <?= date('Y') ?> by <a href="https://github.com/vrkansagara/laminas-adminpanel">Laminas Admin Panel</a>. <?= $this->translate('All rights reserved.') ?>.
            </span>
    </div>
</footer>
<?= $this->inlineScript() ?>
</body>

</html>
