<?php

$this->placeholder('content')->captureStart(); ?>

    <div class="row">
        <div class="col-md-8">
            <?= $this->content; ?>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Layout2</h3>
                </div>

        </div>
    </div>
</div>

<?php
$this->placeholder('content')->captureEnd();
echo $this->partial('layout/layout', ['content' => $this->placeholder('content')]);
?>