<div class="container">
    <h1>Welcome to <span class="zf-green">laminas-adminpanel</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/vrkansagar/laminas-adminpanel" target="_blank">laminas-adminpanel</a>.
        This adminpanel can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/vrkansagara/laminas-adminpanel" target="_blank">Check laminas-adminpanel on GitHub &raquo;</a></p>
</div>
<hr>
<div class="container">
    <div class="row">

        <div class="four columns">
            <div class="card-header">
                <h2 class="card-title">Follow Development</h2>
            </div>


        </div>

        <div class="four columns">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Discover Modules</h2>
                </div>

            </div>
        </div>

        <div class="four columns">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Help &amp; Support</h2>
                </div>

            </div>
        </div>
    </div>
</div>